server:
  port: 8080

spring:
  application:
    name: cloud-drive
  # RabbitMQ配置
  rabbitmq:
    host: 127.0.0.1 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /cloud # 虚拟主机
    username: clouddrive # 用户名
    password: 123 # 密码
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_drive?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  
  mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.xxx.entity
  global-config:
    db-config:
      id-type: auto   # 与原 @GeneratedValue 对齐
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2053312368@qq.com
    password: wvpfiwavjbwydbjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      datebase: 0

# Redisson配置
redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      database: 0
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      connectionMinimumIdleSize: 10
      connectionPoolSize: 64
      dnsMonitoringInterval: 5000

# Sa-Token配置
sa-token:
  # token名称
  token-name: Authorization
  # token有效期
  timeout: 3600
  # token临时有效期
  active-timeout: -1
  # 是否允许同一账号并发登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从请求体里读取token
  is-read-body: true
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: true
  # token前缀
  token-prefix: ""
  # 使用 Redis Jackson DAO 存储 Sa-Token 数据
  dao: redisJackson

# 存储服务配置
storage:
  type: minio  # 当前使用的存储类型：aliyun 或 minio

# OSS配置

# MinIO配置
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: clouddrive
  expiry: 1 # redis 文件信息失效时间 天
  breakpointTime: 1 # 分片地址失效时间 天

# 分片上传配置
app:
  chunk-upload:
    temp-dir: D:/Develop/Codes/cloud-drive/temp/chunks
    chunk-size: 2097152  # 2MB
    max-concurrent: 3
    retry-times: 3
    expire-hours: 24